services:
  next:
    container_name: next
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - ./src/musicalendar:/app
      - /app/node_modules
    ports:
      - 3000:3000
